os: linux

jobs:
  include:
    - name: Test webapp
      language: node_js
      node_js: 16
      cache:
        directories:
          - web/node_modules
      script:
        - cd web 
        - npm install
        - npm test -- --watchAll=false --testResultsProcessor="jest-junit"

    - name: Build webapp
      language: node_js
      node_js: 16
      cache:
        directories:
          - web/node_modules
      script:
        - cd web
        - npm install
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: web/build
        on:
          branch: main

    - name: Build MacOS plugin 
      language: cpp
      compiler: clang
      osx_image: xcode12.5
      os: osx
      install: cmake -S . -B "build"
      script: cmake --build ./build --config Release
      #deploy:
      #  provider: s3
      #  access_key_id: ""
      #  secret_access_key: ""
      #  bucket: "arn:aws:s3:::artefacts-dump"
      #  skip_cleanup: true
      #  local_dir: build

    - name: Build Windows plugin
      language: cpp
      os: windows
      install: cmake -S . -B "build"
      script: cmake --build ./build --config Release
